= Lab Access

For your convenience, this page contains access information to all systems in your lab environment.

[#consoles]
== Graphical Consoles

[cols="1,3,1,1"]
|===
s| Role s| URL s| Tab s| Username
| VS Code | {z_vscode_web_ui_url}[window=_blank] | Codeserver | {z_gitea_web_ui_username}
| Automation controller | {z_ansible_controller_web_ui_url}[window=_blank] | AAP | {z_ansible_controller_admin_username}
| Gitea web UI | {z_gitea_web_ui_url}[window=_blank] | n/a | {z_gitea_web_ui_username}
|===

The password for all systems is: **{z_ansible_controller_admin_password}**

[#ssh]
== SSH Details

Your primary work machine is `bastion`, which is pre-configured for any internal SSH. If you want to SSH into it instead of using VS Code, here is the information:

[cols="1,1,3"]
|===
s|SSH Username s|SSH Password s| SSH Host
|{z_gitea_web_ui_username}
|{z_ansible_controller_admin_password}
|{z_bastion_host_name}
|===

[source,bash,role=execute,subs=attributes+]
.SSH command:
----
ssh {z_gitea_web_ui_username}@{z_bastion_host_name}
----

TIP: the Showroom tab named "Terminal" gives you a similar look & feel as would SSH, without the need to login.
