= You've done it!

Congratulations, you've completed the lab!
We hope you've enjoyed it, here is what you should take with you:

* You've discovered the new UI,
* configured AAP using Ansible itself and the principles of Configuration as Code (CaC) for maximum automation,
* used workflows to orchestrate your automation,
* applied a survey to customize the result,
* used dynamic and constructed inventories to flexibly extend the scope of your automation,
* and applied RBAC and code signing to secure your supply chain!

If you want to redo some of the exercises, or share your experience with others, simply https://www.redhat.com/en/technologies/management/ansible/trial[spin up your own trial instance^], create a RHEL host with `ansible-navigator` and `ansible-sign` installed, and spin up two generic RHEL hosts.
With some adaptation, you should then be able to follow most of the https://rhpds.github.io/showroom-lb1706-advance-feature-of-aap/modules/index.html[(generic) guide available online^].

NOTE: The term "generic" means that hostnames, users and passwords are not adapted to your environment and are only placeholders.
It'll be up to you to apply the right values while reading the guide.

The Git repositories we use in this lab are also freely available:

Lab Project Repo:: https://gitlab.com/ansible-labs-crew/playbooks-adv-controller-2025.git[^]
Webdev Git Repo:: https://gitlab.com/ansible-labs-crew/playbooks-dev.git[^]
Webops Git Repo:: https://gitlab.com/ansible-labs-crew/playbooks-ops.git[^]

CAUTION: You might need to adapt slightly some of the code to your environment to make everything work correctly.

And there is more than Automation Execution to discover in AAP, with https://www.redhat.com/en/technologies/management/ansible/event-driven-ansible[Event Driven Ansible (Decisions)], https://www.redhat.com/en/technologies/management/ansible/content-collections[prepared content] and the many https://www.redhat.com/en/technologies/management/ansible/development-tools[developer tools], your ability to automate becomes limitless.
